AllCops:
  TargetRubyVersion: 2.4
  TargetRailsVersion: 5.2
  ExtraDetails: true
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - bin/*
    - config/**/*
    - db/**/*
    - node_modules/**/*
    - spec/spec_helper.rb

Rails:
  Enabled: true

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - spec/**/*
    - lib/tasks/**/*

Layout/IndentationConsistency:
  EnforcedStyle: rails

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/UnusedBlockArgument:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - Guardfile
    - spec/**/*
    - lib/tasks/**/*

Metrics/LineLength:
  Enabled: true
  Max: 80
  AllowURI: true

Metrics/MethodLength:
  Max: 20

Style/BlockDelimiters:
  Exclude:
    - app/controllers/**/*

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Exclude:
    - app/controllers/**/*

Style/FrozenStringLiteralComment:
  Enabled: false
