AllCops:
  Exclude:
    - Gemfile
    - bin/*
    - config/**/*
    - db/**/*
    - node_modules/**/*
    - spec/spec_helper.rb

Rails:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - spec/**/*

Layout/LeadingCommentSpace:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Exclude:
    - app/controllers/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false
  
Style/StringLiterals:
  Enabled: false
