# https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md

linters:
  ColorKeyword:
    enabled: false

  ColorVariable:
    enabled: false

  Comment:
    enabled: false

  EmptyRule:
    enabled: false

  IdSelector:
    enabled: false

  NestingDepth:
    max_depth: 5

  QualifyingElement:
    enabled: false
