/* Connectivity  */
export const CHANNEL_CONNECTED = 'CHANNEL_CONNECTED'
export const CHANNEL_DISCONNECTED = 'CHANNEL_DISCONNECTED'
export const CHANNEL_RECEIVED = 'CHANNEL_RECEIVED'
export const CHANNEL_PERFORM = 'CHANNEL_PERFORM'

//export const STATEMENT_REQUEST = 'CHANNEL_PERFORM_REQUEST'
/*
export const GEOJSON = 'GEOJSON'
export const GEOJSON_ELEVATIONS_UPDATE = 'GEOJSON_ELEVATIONS_UPDATE'
export const CROSSFILTER_CHANGE = 'CROSSFILTER_CHANGE'
export const GEOJSON_CROSSFILTER = 'GEOJSON_CROSSFILTER'
*/
//export const STATEMENT = 'CHANNEL_PERFORM_REQUEST'

export const DATA = 'DATA'
export const SIDEBAR = 'SIDEBAR'

//export const LIVY_RECEIVED ='LIVY'
