###
# Available countries in Geojson
window.cedefop_names_map = {
"Austria": "Austria"
"Finland": "Finland"
"Albania": "Albania"
"Bosnia and Herz.": "Bosnia and Herz."
"Belgium": "Belgium"
"Switzerland": "Switzerland"
"Bulgaria": "Bulgaria"
"Germany": "Germany"
"Belarus": "Belarus"
"Czech Rep.": "Czech Rep."
"Greenland": "Greenland"
"Finland": "Finland"
"Spain": "Spain"
"Greenland": "Greenland"
"Estonia": "Estonia"
"New Caledonia": "New Caledonia"
"Croatia": "Croatia"
"Hungary": "Hungary"
"Greece": "Greece"
"Italy": "Italy"
"United Kingdom": "United Kingdom"
"Ireland": "Ireland"
"Kosovo": "Kosovo"
"Iceland": "Iceland"
"Latvia": "Latvia"
"Luxembourg": "Luxembourg"
"Lithuania": "Lithuania"
"Moldova": "Moldova"
"Montenegro": "Montenegro"
"Macedonia": "Macedonia"
"Netherlands": "Netherlands"
"Norway": "Norway"
"Portugal": "Portugal"
"Romania": "Romania"
"Russia": "Russia"
"Poland": "Poland"
"Serbia": "Serbia"
"Slovakia": "Slovakia"
"Slovenia": "Slovenia"
"Sweden": "Sweden"
"Ukraine": "Ukraine"
}
###

window.cedefop_names_map = {
  "United Kingdom": "UNITED KINGDOM"
  "Germany":  "DEUTSCHLAND"
  "Italy": "ITALIA"
  "Czech Rep.": "ČESKÁ REPUBLIKA"
  "Ireland": "IRELAND"
}
