# Available countries in Geojson

window.eures_names_map = {
  "Austria": "Austria"
  "Belgium": "Belgium"
  "Bulgaria": "Bulgaria"
  "Croatia": "Croatia"
  "Cyprus": "Cyprus"
  "Czech Rep.": "Czech Republic"
  "Denmark": "Denmark"
  "Estonia": "Estonia"
  "Finland": "Finland"
  "France": "France"
  "Germany": "Germany"
  "Greece": "Greece"
  "Hungary": "Hungary"
  #  "Ireland": "Ireland"
  "Italy": "Italy"
  "Latvia": "Latvia"
  "Lithuania": "Lithuania"
  "Luxembourg": "Luxembourg"
  "Malta": "Malta"
  "Netherlands": "Netherlands"
  #"Norway": "Norway"
  "Poland": "Poland"
  "Portugal": "Portugal"
  "Romania": "Romania"
  "Slovakia": "Slovakia"
  "Slovenia": "Slovenia"
  "Spain": "Spain"
  "Sweden": "Sweden"
  "United Kingdom": "United Kingdom"
}
